### PR TITLE
Centralize the logic about wsl

### LINKED ISSUE #48: Abstract leetcode command

### LINKED ISSUE #54: The path of leetcode binary is wrong when switch between enable/disable wsl.
This is because https://github.com/jdneo/vscode-leetcode/blob/master/src/shared.ts#L7 is never updated according to the setting.

### PR DESCRIPTION
**Pull request by jdneo**
fix #48 
fix #54

### CODE REVIEW

**Comment by jdneo** [comment]
Hi @purocean,

As we have discussed before. We can have some further improvement about the WSL support.

During my own experience, the main problems of current implementation are:
- WSL related logics separate in several different files
- The leetCodeBinaryPath will be wrong if the setting of `enableWSL` is switched by users.

So this is the reason I create a new class: `leetCodeExecutor`, and try to put WSL related logic into this class as much as possible.

Very appreciated if you can help review this PR if you have time. Since this feature is originally contributed by you. 😄

**Comment by purocean** [comment]
@jdneo OK, I'll take a look.

**Comment by purocean** [comment]
Have you tested with enable `useWsl`?

> LeetCode extension need Node.js installed in environment path

It occurs an error in my machine. 

https://github.com/jdneo/vscode-leetcode/blob/8c52f42f37bcc48b0f79210545169e629ec456d3/src/utils/nodeUtils.ts#L10
https://github.com/jdneo/vscode-leetcode/blob/8c52f42f37bcc48b0f79210545169e629ec456d3/src/utils/cpUtils.ts#L11

Looks like have no specific treatment for WSL.

**Comment by jdneo** [comment]
@purocean Nice finding! I'll fix it.

**Comment by jdneo** [comment]
@purocean Updated. Please have a try when you have time.

**Comment by purocean** [comment]
@jdneo 
Work fine for me. 
Just a little wrong text.
> Submitting to LeetCode

https://github.com/jdneo/vscode-leetcode/blob/526cedd1eb52c6383fe1342c9d3b744bde784b39/src/leetCodeExecutor.ts#L109

**Comment by jdneo** [comment]
@purocean Emm, I'm sorry. Anything wrong with "Submitting to LeetCode..."?

**Comment by jdneo** [comment]
Haha, got it.

We can revisit the wording issue if we get user feedbacks in the future.

**Pull request merged**
