### PR TITLE
chore: replace the LeetCode.svg and LeetCode.png

### PR DESCRIPTION
**Pull request by poppinlp**
- Replace the `LeetCode.svg` and `LeetCode.png`
- Add JIEJIAN21 in contributors
- Seems my markdown plugin reformated the table in README.md to make the separator in the same column.

Address #401

### CODE REVIEW

**Comment by jdneo** [comment]
Thanks @poppinlp, could you fix the CI error? 

`ERROR  Images in README.md must come from an HTTPS source: ./resources/LeetCode.png`

**Comment by poppinlp** [comment]
This error is occured by the url of `LeetCode.png` in `README.md` and `README_zh-CN.md`.
I've modified the url to local relative path instead of the file from master branch of github repository.

Actually, I think it's good to use relative path here since we should use the resources from current branch. But seems vsce dose not support it right now according to [this issue](https://github.com/Microsoft/vscode-vsce/issues/192).

I've changed it back to pass the travis CI.

**Comment by jdneo** [comment]
Hey @poppinlp

Just one more question. Now the extension icon and the activity bar icon are both using the new picture. Are we mean to discard the activity bar icon that your friend designed just before?

**Comment by poppinlp** [comment]
I think I made a mistake. I should only replace the image in README. The previous activity icon is much more fits the sidebar. I'll bring it back now.
image

**Pull request merged**
