### PR TITLE
replace icons in extension with vscode icons

### PR DESCRIPTION
**Pull request by hologerry**
For issue [#460](https://github.com/jdneo/vscode-leetcode/issues/460)

### CODE REVIEW

**Comment by jdneo** [comment]
Thanks, will take a look later.

**Comment by jdneo** [comment]
Hey @hologerry.

The globe icon works great from my side. Are you sure it's not working at your side?

image

BTW, I appended a commit to correct the color of the search icon in dark mode.

**Comment by hologerry** [comment]
For the stable VS Code version the globe icon works, however it does not work on Insider VS Code version.
All icons are correct on latest stable VS Code version.

**Comment by jdneo** [comment]
Thanks @hologerry

**Pull request merged**
