### PR TITLE
Bring markdown engine into submission provider

### LINKED ISSUE #388: Actual stdout (console.log) layout enhancement: to display content in multi-line mode.
## 🚀 Feature Proposal

Actual stdout (console.log) layout enhancement: to display content in multi-line mode.

## Motivation

console.log output all in one line, not friendly to program debug. 

e.g., in vs description win:

    stdout: 'l1={"val":1,"next":{"val":8,"next":null}}\nl2={"val":0,"next":null}\nadv=0\n-----\n

while in leetcode page:

    l1={"val":1,"next":{"val":8,"next":null}}
    l2={"val":0,"next":null}
    adv=0
    -----

## Contribution

1. stdout support multi-line mode;
2. convert \n into a new line.

### PR DESCRIPTION
**Pull request by Vigilans**
## Introduction
Fix #388 #427 
Depends on https://github.com/leetcode-tools/leetcode-cli/pull/20

### Demonstration
image
image
image
image

### CODE REVIEW

**Comment by jdneo** [comment]
Is this aim to support #388?

**Comment by Vigilans** [comment]
Yes
Fix #388 Added

**Comment by jdneo** [comment]
@Vigilans `2.6.9` has been released.

**Comment by jdneo** [comment]
Thanks @Vigilans

**Pull request merged**
