### PR TITLE
Support showing description from text document

### PR DESCRIPTION
**Pull request by Vigilans**
Solves #286

Relies on https://github.com/leetcode-tools/leetcode-cli/pull/13

Demonstration:
demo2

### CODE REVIEW

**Comment by jdneo** [comment]
@Vigilans First of all, thank you for the enthusiasm you give.

One thing I have to mentions is that, please do not try to solve multiple issues in one PR. This very hard for tracking the issues.

Could you please revert this PR to make it only solve #287 first. And please let me know what I can do to help you achieve that.

Thanks.

**Comment by Vigilans** [comment]
#287 has already been solved in #289 4 days ago and wait for the `leetcode-cli` dependency update.

This three issues all point to the same thing(comment in #287 is duplicate of #286), and there is no meaning in splitting them: it will only result in a PR of 90% content and a PR with 10% content.

**Comment by Vigilans** [comment]
> Could you please revert this PR to make it only solve #287 first. And please let me know what I can do to help you achieve that.

This PR doesn't solve #287

**Comment by jdneo** [comment]
I see. I've added comments in #289.

But still, I would like to request you to split the PR even it's 10% + 90%. Thank you for your understanding.

**Pull request closed without merging**
